# Generated by Django 3.1.7 on 2021-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.FileField(upload_to='media/ourWork/')),
            ],
        ),
    ]
