# Generated by Django 3.1.7 on 2021-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourwork',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
