# Generated by Django 3.1.7 on 2021-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210222_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworkphoto',
            name='image_after',
            field=models.FileField(blank=True, null=True, upload_to='ourWork/after'),
        ),
        migrations.AlterField(
            model_name='ourworkphoto',
            name='image_before',
            field=models.FileField(blank=True, null=True, upload_to='ourWork/before'),
        ),
    ]
